version: '3.8'

services:
  userservice-app:
    build: ../userservice
    ports:
      - "8080:8080"

  profileservice-app:
    build: ../profileservice
    ports:
      - "8079:8079"

  postservice-app:
    build: ../postservice
    ports:
      - "8081:8081"

  bffservice-app:
    build: .
    ports:
      - "8077:8077"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://bffservice-db:3306/bffservice_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - bffservice-db

  bffservice-db:
    image: mariadb
    ports:
      - "3308:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=bffservice_db
      - MARIADB_USER=user
      - MARIADB_PASSWORD=root
    volumes:
      - bffservice-db-data:/var/lib/mysql

volumes:
  bffservice-db-data:
